### PR TITLE
add archival notice

### PR DESCRIPTION
**Pull request by sertonix**
This adds an archival notice since the repo is not used.

### CODE REVIEW

**Comment by confused-Techie** [comment]
This repo is in fact in use on the [main editor](https://github.com/pulsar-edit/pulsar/blob/master/package.json#L81). As well as quite a few of our other repos.

While we do want to switch our testing platforms, since we haven't yet, we shouldn't archive this repo just yet.

**Comment by sertonix** [comment]
> This repo is in fact in use on the [main editor](https://github.com/pulsar-edit/pulsar/blob/master/package.json#L81). As well as quite a few of our other repos.
> 
> While we do want to switch our testing platforms, since we haven't yet, we shouldn't archive this repo just yet.

Yes [`jasmine-reporters`](https://www.npmjs.com/package/jasmine-reporters) is used but this is not an Atom project. This is one of the forks with no changes.

**Comment by confused-Techie** [comment]
@Sertonix Wow, good catch. But also so so bizarre, that they use `jasmine-reporters` have forked and maintained `jasmine-reporters` but then never used it?

**Review by confused-Techie — APPROVED** [review]
But you're right, this repo has never received a single commit under Atom.

Great find on noticing that, as you clearly see I didn't.

Thanks for contributing

**Pull request merged**
